name: CI

on:
  push:
  schedule:
    - cron:  '0 2 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Start Travis CI build of zabbix-docker-armhf
        env:
          TRAVIS_TOKEN: ${{ secrets.TRAVIS_TOKEN }}
        run: ./build-zabbix-arm.sh
